### ISSUE TITLE
Rename package on hex.pm

### ISSUE THREAD

**Issue by tanguilp** [resuelve/wax#16]
Hello,

I'm the creator of https://github.com/tanguilp/wax and in the process of releasing a new version. As part of the release, I plan to publish it on hex.pm. However, it seems your library already use the wax name, also this is not the name of the current library.

This might cause confusion, as for example: https://github.com/tanguilp/wax/issues/16

This is why I respectfully ask you if you could rename your package's name on hex.pm

**Comment by oscarolbe** [comment]
Sorry @tanguilp. We have no plans to rename it.
It will cause confusion in ours.

**Comment by tanguilp** [comment]
Thanks for the swift answer!

However I'm respectfully and one last time asking you to reconsider your position, for the following reasons:
- Looks like it's already causing confusion (2 people so far)
- Wax-Webauthn looks more known than Wax-whatsapp_api (for instance looking at the people following it on Github)
- The Wax name was already in use and announced by the project I develop as of [February, 2019](https://elixirforum.com/t/wax-webauthn-for-elixir/20073) and it can be seen as a _bad practice_ to reuse library names in a given language

Cheers!
